DROP TABLE PERSON_DOCUMENTS;
DROP TABLE PHONE_NUMBER;
DROP TABLE PERSON;

CREATE TABLE IF NOT EXISTS PERSON (
   id INT NOT NULL,
   name VARCHAR(50) NOT NULL,
   birth_date DATE NOT NULL,
   height NUMERIC,
   weight NUMERIC,
   created TIMESTAMP NOT NULL,
   updated TIMESTAMP NOT NULL,
   version INT NOT NULL
);

CREATE TABLE IF NOT EXISTS PERSON_DOCUMENTS (
   id INT NOT NULL,
   passport VARCHAR(36) NOT NULL,
   driver_licence VARCHAR(36),
   national_id VARCHAR(36),
   version INT NOT NULL
);

CREATE TABLE IF NOT EXISTS PHONE_NUMBER (
   id INT NOT NULL,
   person INT NOT NULL,
   type VARCHAR(10) NOT NULL,
   number VARCHAR(35),
   version INT NOT NULL
);
